export const countryList = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CD", name: "Congo (DRC)" },
  { code: "CG", name: "Congo (Republic)" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KP", name: "Korea, North" },
  { code: "KR", name: "Korea, South" },
  { code: "XK", name: "Kosovo" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "São Tomé and Príncipe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

// All country calling codes
export const countryCodes = [
  { code: "AF", dialCode: "+93", name: "Afghanistan" },
  { code: "AL", dialCode: "+355", name: "Albania" },
  { code: "DZ", dialCode: "+213", name: "Algeria" },
  { code: "AD", dialCode: "+376", name: "Andorra" },
  { code: "AO", dialCode: "+244", name: "Angola" },
  { code: "AG", dialCode: "+1", name: "Antigua and Barbuda" },
  { code: "AR", dialCode: "+54", name: "Argentina" },
  { code: "AM", dialCode: "+374", name: "Armenia" },
  { code: "AU", dialCode: "+61", name: "Australia" },
  { code: "AT", dialCode: "+43", name: "Austria" },
  { code: "AZ", dialCode: "+994", name: "Azerbaijan" },
  { code: "BS", dialCode: "+1", name: "Bahamas" },
  { code: "BH", dialCode: "+973", name: "Bahrain" },
  { code: "BD", dialCode: "+880", name: "Bangladesh" },
  { code: "BB", dialCode: "+1", name: "Barbados" },
  { code: "BY", dialCode: "+375", name: "Belarus" },
  { code: "BE", dialCode: "+32", name: "Belgium" },
  { code: "BZ", dialCode: "+501", name: "Belize" },
  { code: "BJ", dialCode: "+229", name: "Benin" },
  { code: "BT", dialCode: "+975", name: "Bhutan" },
  { code: "BO", dialCode: "+591", name: "Bolivia" },
  { code: "BA", dialCode: "+387", name: "Bosnia and Herzegovina" },
  { code: "BW", dialCode: "+267", name: "Botswana" },
  { code: "BR", dialCode: "+55", name: "Brazil" },
  { code: "BN", dialCode: "+673", name: "Brunei" },
  { code: "BG", dialCode: "+359", name: "Bulgaria" },
  { code: "BF", dialCode: "+226", name: "Burkina Faso" },
  { code: "BI", dialCode: "+257", name: "Burundi" },
  { code: "CV", dialCode: "+238", name: "Cabo Verde" },
  { code: "KH", dialCode: "+855", name: "Cambodia" },
  { code: "CM", dialCode: "+237", name: "Cameroon" },
  { code: "CA", dialCode: "+1", name: "Canada" },
  { code: "CF", dialCode: "+236", name: "Central African Republic" },
  { code: "TD", dialCode: "+235", name: "Chad" },
  { code: "CL", dialCode: "+56", name: "Chile" },
  { code: "CN", dialCode: "+86", name: "China" },
  { code: "CO", dialCode: "+57", name: "Colombia" },
  { code: "KM", dialCode: "+269", name: "Comoros" },
  { code: "CD", dialCode: "+243", name: "Congo (DRC)" },
  { code: "CG", dialCode: "+242", name: "Congo (Republic)" },
  { code: "CR", dialCode: "+506", name: "Costa Rica" },
  { code: "CI", dialCode: "+225", name: "Côte d'Ivoire" },
  { code: "HR", dialCode: "+385", name: "Croatia" },
  { code: "CU", dialCode: "+53", name: "Cuba" },
  { code: "CY", dialCode: "+357", name: "Cyprus" },
  { code: "CZ", dialCode: "+420", name: "Czech Republic" },
  { code: "DK", dialCode: "+45", name: "Denmark" },
  { code: "DJ", dialCode: "+253", name: "Djibouti" },
  { code: "DM", dialCode: "+1", name: "Dominica" },
  { code: "DO", dialCode: "+1", name: "Dominican Republic" },
  { code: "EC", dialCode: "+593", name: "Ecuador" },
  { code: "EG", dialCode: "+20", name: "Egypt" },
  { code: "SV", dialCode: "+503", name: "El Salvador" },
  { code: "GQ", dialCode: "+240", name: "Equatorial Guinea" },
  { code: "ER", dialCode: "+291", name: "Eritrea" },
  { code: "EE", dialCode: "+372", name: "Estonia" },
  { code: "SZ", dialCode: "+268", name: "Eswatini" },
  { code: "ET", dialCode: "+251", name: "Ethiopia" },
  { code: "FJ", dialCode: "+679", name: "Fiji" },
  { code: "FI", dialCode: "+358", name: "Finland" },
  { code: "FR", dialCode: "+33", name: "France" },
  { code: "GA", dialCode: "+241", name: "Gabon" },
  { code: "GM", dialCode: "+220", name: "Gambia" },
  { code: "GE", dialCode: "+995", name: "Georgia" },
  { code: "DE", dialCode: "+49", name: "Germany" },
  { code: "GH", dialCode: "+233", name: "Ghana" },
  { code: "GR", dialCode: "+30", name: "Greece" },
  { code: "GD", dialCode: "+1", name: "Grenada" },
  { code: "GT", dialCode: "+502", name: "Guatemala" },
  { code: "GN", dialCode: "+224", name: "Guinea" },
  { code: "GW", dialCode: "+245", name: "Guinea-Bissau" },
  { code: "GY", dialCode: "+592", name: "Guyana" },
  { code: "HT", dialCode: "+509", name: "Haiti" },
  { code: "HN", dialCode: "+504", name: "Honduras" },
  { code: "HU", dialCode: "+36", name: "Hungary" },
  { code: "IS", dialCode: "+354", name: "Iceland" },
  { code: "IN", dialCode: "+91", name: "India" },
  { code: "ID", dialCode: "+62", name: "Indonesia" },
  { code: "IR", dialCode: "+98", name: "Iran" },
  { code: "IQ", dialCode: "+964", name: "Iraq" },
  { code: "IE", dialCode: "+353", name: "Ireland" },
  { code: "IL", dialCode: "+972", name: "Israel" },
  { code: "IT", dialCode: "+39", name: "Italy" },
  { code: "JM", dialCode: "+1", name: "Jamaica" },
  { code: "JP", dialCode: "+81", name: "Japan" },
  { code: "JO", dialCode: "+962", name: "Jordan" },
  { code: "KZ", dialCode: "+7", name: "Kazakhstan" },
  { code: "KE", dialCode: "+254", name: "Kenya" },
  { code: "KI", dialCode: "+686", name: "Kiribati" },
  { code: "KP", dialCode: "+850", name: "Korea, North" },
  { code: "KR", dialCode: "+82", name: "Korea, South" },
  { code: "XK", dialCode: "+383", name: "Kosovo" },
  { code: "KW", dialCode: "+965", name: "Kuwait" },
  { code: "KG", dialCode: "+996", name: "Kyrgyzstan" },
  { code: "LA", dialCode: "+856", name: "Laos" },
  { code: "LV", dialCode: "+371", name: "Latvia" },
  { code: "LB", dialCode: "+961", name: "Lebanon" },
  { code: "LS", dialCode: "+266", name: "Lesotho" },
  { code: "LR", dialCode: "+231", name: "Liberia" },
  { code: "LY", dialCode: "+218", name: "Libya" },
  { code: "LI", dialCode: "+423", name: "Liechtenstein" },
  { code: "LT", dialCode: "+370", name: "Lithuania" },
  { code: "LU", dialCode: "+352", name: "Luxembourg" },
  { code: "MG", dialCode: "+261", name: "Madagascar" },
  { code: "MW", dialCode: "+265", name: "Malawi" },
  { code: "MY", dialCode: "+60", name: "Malaysia" },
  { code: "MV", dialCode: "+960", name: "Maldives" },
  { code: "ML", dialCode: "+223", name: "Mali" },
  { code: "MT", dialCode: "+356", name: "Malta" },
  { code: "MH", dialCode: "+692", name: "Marshall Islands" },
  { code: "MR", dialCode: "+222", name: "Mauritania" },
  { code: "MU", dialCode: "+230", name: "Mauritius" },
  { code: "MX", dialCode: "+52", name: "Mexico" },
  { code: "FM", dialCode: "+691", name: "Micronesia" },
  { code: "MD", dialCode: "+373", name: "Moldova" },
  { code: "MC", dialCode: "+377", name: "Monaco" },
  { code: "MN", dialCode: "+976", name: "Mongolia" },
  { code: "ME", dialCode: "+382", name: "Montenegro" },
  { code: "MA", dialCode: "+212", name: "Morocco" },
  { code: "MZ", dialCode: "+258", name: "Mozambique" },
  { code: "MM", dialCode: "+95", name: "Myanmar" },
  { code: "NA", dialCode: "+264", name: "Namibia" },
  { code: "NR", dialCode: "+674", name: "Nauru" },
  { code: "NP", dialCode: "+977", name: "Nepal" },
  { code: "NL", dialCode: "+31", name: "Netherlands" },
  { code: "NZ", dialCode: "+64", name: "New Zealand" },
  { code: "NI", dialCode: "+505", name: "Nicaragua" },
  { code: "NE", dialCode: "+227", name: "Niger" },
  { code: "NG", dialCode: "+234", name: "Nigeria" },
  { code: "MK", dialCode: "+389", name: "North Macedonia" },
  { code: "NO", dialCode: "+47", name: "Norway" },
  { code: "OM", dialCode: "+968", name: "Oman" },
  { code: "PK", dialCode: "+92", name: "Pakistan" },
  { code: "PW", dialCode: "+680", name: "Palau" },
  { code: "PS", dialCode: "+970", name: "Palestine" },
  { code: "PA", dialCode: "+507", name: "Panama" },
  { code: "PG", dialCode: "+675", name: "Papua New Guinea" },
  { code: "PY", dialCode: "+595", name: "Paraguay" },
  { code: "PE", dialCode: "+51", name: "Peru" },
  { code: "PH", dialCode: "+63", name: "Philippines" },
  { code: "PL", dialCode: "+48", name: "Poland" },
  { code: "PT", dialCode: "+351", name: "Portugal" },
  { code: "QA", dialCode: "+974", name: "Qatar" },
  { code: "RO", dialCode: "+40", name: "Romania" },
  { code: "RU", dialCode: "+7", name: "Russia" },
  { code: "RW", dialCode: "+250", name: "Rwanda" },
  { code: "KN", dialCode: "+1", name: "Saint Kitts and Nevis" },
  { code: "LC", dialCode: "+1", name: "Saint Lucia" },
  { code: "VC", dialCode: "+1", name: "Saint Vincent and the Grenadines" },
  { code: "WS", dialCode: "+685", name: "Samoa" },
  { code: "SM", dialCode: "+378", name: "San Marino" },
  { code: "ST", dialCode: "+239", name: "São Tomé and Príncipe" },
  { code: "SA", dialCode: "+966", name: "Saudi Arabia" },
  { code: "SN", dialCode: "+221", name: "Senegal" },
  { code: "RS", dialCode: "+381", name: "Serbia" },
  { code: "SC", dialCode: "+248", name: "Seychelles" },
  { code: "SL", dialCode: "+232", name: "Sierra Leone" },
  { code: "SG", dialCode: "+65", name: "Singapore" },
  { code: "SK", dialCode: "+421", name: "Slovakia" },
  { code: "SI", dialCode: "+386", name: "Slovenia" },
  { code: "SB", dialCode: "+677", name: "Solomon Islands" },
  { code: "SO", dialCode: "+252", name: "Somalia" },
  { code: "ZA", dialCode: "+27", name: "South Africa" },
  { code: "SS", dialCode: "+211", name: "South Sudan" },
  { code: "ES", dialCode: "+34", name: "Spain" },
  { code: "LK", dialCode: "+94", name: "Sri Lanka" },
  { code: "SD", dialCode: "+249", name: "Sudan" },
  { code: "SR", dialCode: "+597", name: "Suriname" },
  { code: "SE", dialCode: "+46", name: "Sweden" },
  { code: "CH", dialCode: "+41", name: "Switzerland" },
  { code: "SY", dialCode: "+963", name: "Syria" },
  { code: "TW", dialCode: "+886", name: "Taiwan" },
  { code: "TJ", dialCode: "+992", name: "Tajikistan" },
  { code: "TZ", dialCode: "+255", name: "Tanzania" },
  { code: "TH", dialCode: "+66", name: "Thailand" },
  { code: "TL", dialCode: "+670", name: "Timor-Leste" },
  { code: "TG", dialCode: "+228", name: "Togo" },
  { code: "TO", dialCode: "+676", name: "Tonga" },
  { code: "TT", dialCode: "+1", name: "Trinidad and Tobago" },
  { code: "TN", dialCode: "+216", name: "Tunisia" },
  { code: "TR", dialCode: "+90", name: "Turkey" },
  { code: "TM", dialCode: "+993", name: "Turkmenistan" },
  { code: "TV", dialCode: "+688", name: "Tuvalu" },
  { code: "UG", dialCode: "+256", name: "Uganda" },
  { code: "UA", dialCode: "+380", name: "Ukraine" },
  { code: "AE", dialCode: "+971", name: "United Arab Emirates" },
  { code: "GB", dialCode: "+44", name: "United Kingdom" },
  { code: "US", dialCode: "+1", name: "United States" },
  { code: "UY", dialCode: "+598", name: "Uruguay" },
  { code: "UZ", dialCode: "+998", name: "Uzbekistan" },
  { code: "VU", dialCode: "+678", name: "Vanuatu" },
  { code: "VA", dialCode: "+39", name: "Vatican City" },
  { code: "VE", dialCode: "+58", name: "Venezuela" },
  { code: "VN", dialCode: "+84", name: "Vietnam" },
  { code: "YE", dialCode: "+967", name: "Yemen" },
  { code: "ZM", dialCode: "+260", name: "Zambia" },
  { code: "ZW", dialCode: "+263", name: "Zimbabwe" },
];
